#!/usr/bin/env bash
# Example: How to use the Kubernetes + AWS EKS flake template
#
# This script demonstrates the typical workflow for using this template

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Kubernetes + AWS EKS Flake Template - Usage Example"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Method 1: Pre-export environment variables (recommended for scripts)"
echo "--------------------------------------------------------------------"
echo "export AWS_ACCESS_KEY_ID='ASIA...'"
echo "export AWS_SECRET_ACCESS_KEY='wJalr...'"
echo "export AWS_SESSION_TOKEN='IQoJb3JpZ2lu...'"
echo "nix develop"
echo ""
echo "Method 2: Interactive prompts (easiest for manual use)"
echo "-------------------------------------------------------"
echo "nix develop"
echo "# You'll be prompted to enter each credential interactively"
echo ""
echo "Step 1: Enter the development environment"
echo "----------------------------------------"
echo "nix develop"
echo ""
echo "Step 2: Configure kubectl for your EKS cluster"
echo "----------------------------------------"
echo "aws eks update-kubeconfig --name my-cluster --region us-east-1"
echo ""
echo "Step 3: Verify connection"
echo "----------------------------------------"
echo "kubectl cluster-info"
echo "check-aws-token"
echo ""
echo "Step 4: Start exploring with k9s"
echo "----------------------------------------"
echo "k9s"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 Tips:"
echo "  - The template supports both pre-exported env vars and interactive prompts"
echo "  - Secret and token prompts use silent input for security"
echo "  - Session tokens typically expire after 1 hour"
echo "  - Run 'check-aws-token' to verify credentials"
echo "  - Exit and re-enter shell with fresh credentials when expired"
echo "  - Customize package list in flake.nix"
echo "  - Change tokenValidityDuration in flake.nix if needed"
